[package]
name = "layer-wasi"
description = "WASI bindings for creating Wasm component AVS applications on Layer."
version = "0.1.1"
edition = { workspace = true }
#authors = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
wasi = { workspace = true }
wstd = { workspace = true }
